# https://taskfile.dev

version: "3"

dotenv:
  - ".env"

tasks:
  prepare_dirs:
    dir: ./store
    cmds:
      - mkdir -p ./store/incoming-esaf
      - mkdir -p ./store/incoming-collection
    generates:
      - ./store
  build_dropbox:
    sources:
      - ./app/**/*.kt
    cmds:
      - gradle jar
      -  cp ./app/build/libs/app-all.jar ./openbis/src/esaf/lib
    generates:
      - ./openbis/src/esaf/app-all.jar
  build:
    cmds:
      - docker compose build
    sources:
      - docker_compose.yml
      - initialiser/Dockerfile
      - openbis/Dockerfile
    deps:
      - prepare_dirs
  start_openbis:
    cmds:
      - docker compose up -d openbis --no-deps --no-recreate --wait
    deps:
      - build
    status:
      - ./openbis/check_health.sh https://${OPENBIS_HOST}:${OPENBIS_PORT}
  change_store_permissions:
    cmds:
      - docker compose exec openbis chmod 777 ${DSS_PATH}/incoming-collection
    deps:
      - start_openbis
    status:
      - docker compose exec openbis stat -c '%a' ${DSS_PATH}/incoming-collection | grep -q 2777
  start_initialiser:
    cmds:
      - docker compose up -d initialiser --no-deps --no-recreate
    status:
      - docker compose ps --status=running | grep -qF "initialiser"

  initialise_masterdata:
    cmds:
      - docker compose exec initialiser python3 ./initialise_masterdata.py -s https://openbis -u ${OPENBIS_USER} -p ${OPENBIS_PASSWORD}
    deps:
      - start_openbis
      - start_initialiser
    sources:
      - initialiser/initialise_masterdata.py
    status:
      - docker compose exec initialiser python3 ./initialise_masterdata.py -s https://openbis -u ${OPENBIS_USER} -p ${OPENBIS_PASSWORD} --check
  move:
    cmds:
      - mv $(./make_upload.sh) ./store/incoming-esaf
    deps:
      - change_store_permissions
      - initialise_masterdata
      - prepare_dirs
  restart_dss:
    deps:
      - build
    cmds:
      - docker compose exec openbis gosu openbis /home/openbis/openbis/bin/dssdown.sh
      - docker compose exec openbis gosu openbis /home/openbis/openbis/bin/dssup.sh

  follow_logs:
    cmds:
      - docker compose exec openbis tail -n 200 /home/openbis/openbis_state/dss_logs/startup_log.txt -n 200 /home/openbis/openbis_state/dss_logs/datastore_server_log.txt
    deps:
      - move
      #- restart_dss
