# https://taskfile.dev

version: "3"

dotenv:
  - ".env"

tasks:
  prepare_dirs:
    dir: ./store
    cmds:
      - ls ./store/
    generates:
      - ./store
  build:
    cmds:
      - docker compose build
    sources:
      - docker_compose.yml
      - initialiser/Dockerfile
      - openbis/Dockerfile
    deps:
      - prepare_dirs
  start_openbis:
    cmds:
      - docker compose up -d openbis --no-deps
      - touch openbis.done
    deps:
      - build
    status:
      - ./openbis/check_health.sh https://${OPENBIS_HOST}:${OPENBIS_PORT}
  change_store_permissions:
    cmds:
      - docker compose exec openbis chmod 777 ${DSS_PATH}/incoming-collection
    deps:
      - start_openbis
    status:
      - docker compose exec openbis stat -c '%a' ${DSS_PATH}/incoming-collection | grep -q 2777
  start_initialiser:
    cmds:
      - docker compose up -d initialiser --no-deps
    status:
      - docker compose ps --status=running | grep -qF "initialiser"

  initialise_masterdata:
    cmds:
      - docker compose exec initialiser python3 ./initialise_masterdata.py -s https://openbis -u ${OPENBIS_USER} -p {OPENBIS_PASSWORD}
    deps:
      - start_openbis
      - start_initialiser
    sources:
      - initialiser/initialise_masterdata.py
  move:
    cmds:
      - cp $(mktemp XXX.txt) {{.USER_WORKING_DIR}}/store/incoming-collection/
    deps:
      - change_store_permissions
      - initialise_masterdata
  follow_logs:
    cmds:
      - docker compose exec openbis tail -f -n 50 /home/openbis/openbis_state/dss_logs/startup_log.txt /home/openbis/openbis_state/dss_logs/datastore_server_log.txt
    deps:
      - move
